### ISSUE TITLE
Movement detection inconsistency

### ISSUE THREAD

**Issue by abdallahalsamman** [mgechev/movement.js#7]
![success-maybe](https://user-images.githubusercontent.com/12014839/50541823-9566b380-0bb6-11e9-8c2d-0b6763053e15.gif)
![failure](https://user-images.githubusercontent.com/12014839/50541824-9697e080-0bb6-11e9-9dde-1aec5adbbfcb.gif)
 that was a good workout 😂

**Comment by mgechev** [comment]
This experiment has its limitations. For a more advanced algorithm, I'd recommend you to look at a CNN with something like tensorflow.js. Here's a blog post for getting started https://blog.mgechev.com/2018/10/20/transfer-learning-tensorflow-js-data-augmentation-mobile-net/
